-- MySQL Script generated by MySQL Workbench
-- Wed May 27 01:11:13 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ramp_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ramp_db` ;

-- -----------------------------------------------------
-- Schema ramp_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ramp_db` DEFAULT CHARACTER SET utf8 ;
USE `ramp_db` ;

-- -----------------------------------------------------
-- Table `ramp_db`.`AccountType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ramp_db`.`AccountType` ;

CREATE TABLE IF NOT EXISTS `ramp_db`.`AccountType` (
  `key` INT(11) NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`key`),
  UNIQUE INDEX `key_UNIQUE` (`key` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Data for table `AccountType`
-- -----------------------------------------------------
INSERT INTO `AccountType` (`key`, `description`) VALUES
(1, 'Registered'),
(2, 'User'),
(3, 'Affiliate'),
(4, 'Administrator'),
(5, 'Administrator Manager'),
(6, 'System Administrator');

-- -----------------------------------------------------
-- Table `ramp_db`.`LoginAccount`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ramp_db`.`LoginAccount` ;

CREATE TABLE IF NOT EXISTS `ramp_db`.`LoginAccount` (
  `auPK` VARCHAR(45) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `accountType` INT(11) NOT NULL DEFAULT '1',
  `encryptedPassword` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`auPK`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  INDEX `fk_Account_typeID` (`accountType` ASC) VISIBLE,
  UNIQUE INDEX `auPK_UNIQUE` (`auPK` ASC) VISIBLE,
  CONSTRAINT `fk_Account_typeID`
    FOREIGN KEY (`accountType`)
    REFERENCES `ramp_db`.`AccountType` (`key`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ramp_db`.`Country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ramp_db`.`Country` ;

CREATE TABLE IF NOT EXISTS `ramp_db`.`Country` (
  `nid` INT(3) NOT NULL,
  `code` VARCHAR(2) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `sageCode` VARCHAR(5) NULL DEFAULT NULL,
  PRIMARY KEY (`code`),
  UNIQUE INDEX `code` (`code` ASC) VISIBLE,
  UNIQUE INDEX `nid` (`nid` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ramp_db`.`Person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ramp_db`.`Person` ;

CREATE TABLE IF NOT EXISTS `ramp_db`.`Person` (
  `uname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `honorificPrefix` VARCHAR(45) NULL DEFAULT NULL,
  `givenName` VARCHAR(45) NULL DEFAULT NULL,
  `additionalNames` VARCHAR(45) NULL DEFAULT NULL,
  `familyName` VARCHAR(45) NULL DEFAULT NULL,
  `postOfficeBox` VARCHAR(45) NULL DEFAULT NULL,
  `streetAddress` VARCHAR(45) NULL DEFAULT NULL,
  `extendedAddress` VARCHAR(45) NULL DEFAULT NULL,
  `locality` VARCHAR(45) NULL DEFAULT NULL,
  `region` VARCHAR(45) NULL DEFAULT NULL,
  `postalCode` VARCHAR(45) NULL DEFAULT NULL,
  `country` VARCHAR(2) NULL DEFAULT NULL,
  `telephone` VARCHAR(45) NULL DEFAULT NULL,
  `mobile` VARCHAR(45) NULL DEFAULT NULL,
  `fax` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`uname`),
  INDEX `fk_Person_country` (`country` ASC) VISIBLE,
  UNIQUE INDEX `uname_UNIQUE` (`uname` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  CONSTRAINT `fk_Person_country`
    FOREIGN KEY (`country`)
    REFERENCES `ramp_db`.`Country` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
