-- MySQL Script generated by MySQL Workbench
-- Wed May 27 01:11:13 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ramp_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ramp_db` ;

-- -----------------------------------------------------
-- Schema ramp_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ramp_db` DEFAULT CHARACTER SET utf8 ;
USE `ramp_db` ;

-- -----------------------------------------------------
-- Table `ramp_db`.`AccountType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ramp_db`.`LoginAccountType` ;

CREATE TABLE IF NOT EXISTS `ramp_db`.`LoginAccountType` (
  `key` INT(11) NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`key`),
  UNIQUE INDEX `key_UNIQUE` (`key` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Data for table `AccountType`
-- -----------------------------------------------------
INSERT INTO `LoginAccountType` (`key`, `description`) VALUES
(1, 'Registered'),
(2, 'User'),
(3, 'Affiliate'),
(4, 'Administrator'),
(5, 'Administrator Manager'),
(6, 'System Administrator');

-- -----------------------------------------------------
-- Table `ramp_db`.`LoginAccount`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ramp_db`.`LoginAccount` ;

CREATE TABLE IF NOT EXISTS `ramp_db`.`LoginAccount` (
  `auPK` VARCHAR(45) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `accountType` INT(11) NOT NULL DEFAULT '1',
  `encryptedPassword` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`auPK`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  UNIQUE INDEX `auPK_UNIQUE` (`auPK` ASC) VISIBLE,
  INDEX `fk_Account_typeID` (`accountType` ASC) VISIBLE,
  CONSTRAINT `fk_Account_typeID`
    FOREIGN KEY (`accountType`)
    REFERENCES `ramp_db`.`LoginAccountType` (`key`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ramp_db`.`Country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ramp_db`.`Country` ;

CREATE TABLE IF NOT EXISTS `ramp_db`.`Country` (
  `code` VARCHAR(2) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`code`),
  UNIQUE INDEX `code` (`code` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Data for table `Country`
-- -----------------------------------------------------
INSERT INTO `Country` (`code`, `name`) VALUES
('AT', 'AUSTRIA'),
('BE', 'BELGIUM'),
('HR', 'CROATIA'),
('CY', 'CYPRUS'),
('CZ', 'CZECH REPUBLIC'),
('DK', 'DENMARK'),
('EE', 'ESTONIA'),
('FI', 'FINLAND'),
('FR', 'FRANCE'),
('DE', 'GERMANY'),
('GR', 'GREECE'),
('HU', 'HUNGARY'),
('IS', 'ICELAND'),
('IE', 'IRELAND'),
('IT', 'ITALY'),
('LV', 'LATVIA'),
('LT', 'LITHUANIA'),
('LU', 'LUXEMBOURG'),
('MT', 'MALTA'),
('NL', 'NETHERLANDS'),
('PL', 'POLAND'),
('SK', 'SLOVAKIA'),
('SI', 'SLOVENIA'),
('ES', 'SPAIN'),
('SE', 'SWEDEN'),
('TR', 'TURKEY'),
('UK', 'UNITED KINGDOM');


-- -----------------------------------------------------
-- Table `ramp_db`.`Person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ramp_db`.`Person` ;

CREATE TABLE IF NOT EXISTS `ramp_db`.`Person` (
  `uname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `honorificPrefix` VARCHAR(45) NULL DEFAULT NULL,
  `givenName` VARCHAR(45) NULL DEFAULT NULL,
  `additionalNames` VARCHAR(45) NULL DEFAULT NULL,
  `familyName` VARCHAR(45) NULL DEFAULT NULL,
  `honorificSuffix` VARCHAR(45) NULL DEFAULT NULL,
  `postalAddressCode` VARCHAR(45) NULL DEFAULT NULL,
  `primaryPhoneNumber` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`uname`),
  UNIQUE INDEX `uname_UNIQUE` (`uname` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Table `ramp_db`.`Address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ramp_db`.`Address` ;

CREATE TABLE IF NOT EXISTS `ramp_db`.`Address` (
  `postOfficeBox` VARCHAR(45) NULL DEFAULT NULL,
  `extendedAddress` VARCHAR(45) NOT NULL,
  `streetAddress` VARCHAR(45) NULL DEFAULT NULL,
  `locality` VARCHAR(45) NULL DEFAULT NULL,
  `region` VARCHAR(45) NULL DEFAULT NULL,
  `postalCode` VARCHAR(45) NOT NULL,
  `countryCode` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`countryCode`,`postalCode`,`extendedAddress`),
  INDEX `fk_address_countryCode` (`countryCode` ASC) VISIBLE,
  INDEX `fk__address_postalCode` (`postalCode` ASC) VISIBLE,
  INDEX `fk__address_extendedAddress` (`extendedAddress` ASC) VISIBLE,
  CONSTRAINT `fk_Address_country`
    FOREIGN KEY (`countryCode`)
    REFERENCES `ramp_db`.`Country` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
