-- MySQL Script generated by MySQL Workbench
-- Wed May 27 01:11:13 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ramp_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ramp_db` ;

-- -----------------------------------------------------
-- Schema ramp_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ramp_db` DEFAULT CHARACTER SET utf8 ;
USE `ramp_db`;

-- -----------------------------------------------------
-- Table `ramp_db`.`AccountType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ramp_db`.`LoginAccountType` ;

CREATE TABLE IF NOT EXISTS `ramp_db`.`LoginAccountType` (
  `id` TINYINT NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Data for table `AccountType`
-- -----------------------------------------------------
INSERT INTO `LoginAccountType` (`id`, `value`) VALUES
(1, 'Registered'),
(2, 'User'),
(3, 'Affiliate'),
(4, 'Administrator'),
(5, 'Administrator Manager'),
(6, 'System Administrator');

-- -----------------------------------------------------
-- Table `ramp_db`.`LoginAccount`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ramp_db`.`LoginAccount` ;

CREATE TABLE IF NOT EXISTS `ramp_db`.`LoginAccount` (
  `auPK` VARCHAR(45) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `loginAccountTypeID` TINYINT NOT NULL DEFAULT '1',
  `encryptedPassword` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`auPK`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  UNIQUE INDEX `auPK_UNIQUE` (`auPK` ASC) VISIBLE,
  INDEX `fk_account_typeID` (`loginAccountTypeID` ASC) VISIBLE,
  CONSTRAINT `fk_Account_type`
    FOREIGN KEY (`loginAccountTypeID`)
    REFERENCES `ramp_db`.`LoginAccountType` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `ramp_db`.`Country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ramp_db`.`Country` ;

CREATE TABLE IF NOT EXISTS `ramp_db`.`Country` (
  `code` VARCHAR(2) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`code`),
  UNIQUE INDEX `code` (`code` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Data for table `Country`
-- -----------------------------------------------------
INSERT INTO `Country` (`code`, `name`) VALUES
('AT', 'AUSTRIA'),
('BE', 'BELGIUM'),
('HR', 'CROATIA'),
('CY', 'CYPRUS'),
('CZ', 'CZECH REPUBLIC'),
('DK', 'DENMARK'),
('EE', 'ESTONIA'),
('FI', 'FINLAND'),
('FR', 'FRANCE'),
('DE', 'GERMANY'),
('GR', 'GREECE'),
('HU', 'HUNGARY'),
('IS', 'ICELAND'),
('IE', 'IRELAND'),
('IT', 'ITALY'),
('LV', 'LATVIA'),
('LT', 'LITHUANIA'),
('LU', 'LUXEMBOURG'),
('MT', 'MALTA'),
('NL', 'NETHERLANDS'),
('PL', 'POLAND'),
('SK', 'SLOVAKIA'),
('SI', 'SLOVENIA'),
('ES', 'SPAIN'),
('SE', 'SWEDEN'),
('TR', 'TURKEY'),
('GB', 'UNITED KINGDOM');

-- -----------------------------------------------------
-- Table `ramp_db`.`Person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ramp_db`.`Person` ;

CREATE TABLE IF NOT EXISTS `ramp_db`.`Person` (
  `uname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `honorificPrefix` VARCHAR(45) NULL DEFAULT NULL,
  `givenName` VARCHAR(45) NULL DEFAULT NULL,
  `additionalNames` VARCHAR(45) NULL DEFAULT NULL,
  `familyName` VARCHAR(45) NULL DEFAULT NULL,
  `honorificSuffix` VARCHAR(45) NULL DEFAULT NULL,
-- `homeAddressKEY` VARCHAR(15) NULL DEFAULT NULL,
  `FK_homeAddress_countryCode` VARCHAR(2) DEFAULT NULL,
  `FK_homeAddress_postalCode` VARCHAR(15) DEFAULT NULL,
  `FK_homeAddress_deliveryPointSuffix` VARCHAR(2) DEFAULT NULL,
-- `uniAddressKEY` VARCHAR(15) NULL DEFAULT NULL,
-- `primaryPhoneNumberKEY` VARCHAR(15) NULL DEFAULT NULL,
  PRIMARY KEY (`uname`),
  UNIQUE INDEX `uname_UNIQUE` (`uname` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `ramp_db`.`Address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ramp_db`.`Address` ;

CREATE TABLE IF NOT EXISTS `ramp_db`.`Address` (
  `countryCode` VARCHAR(2) NOT NULL, -- (GB)
  `postalCode` VARCHAR(15) NOT NULL, -- (SO16 8EL)
    -- UK PostCode REGEX max 8chars | US ZIP+4 10chars
    -- ^(?![QVX])[A-Z]{1}(?![I])[A-Y0-9]{1}[0-9]{1}[ABCDEFGHJKPSTUVWX0-9]{0,1}\s[0-9]{1}(?![CIKMOV])[A-Z]{2}$
  `deliveryPointSuffix` VARCHAR(2) NOT NULL,
  -- `addressFileID` VARCHAR(15) NOT NULL,
  -- `extendedAddress` VARCHAR(45) NOT NULL, -- PremisesElements (157)
  `subBuildingName` VARCHAR(30) NULL DEFAULT NULL,
  `buildingName` VARCHAR(50) NULL DEFAULT NULL,
  `buildingNumber` SMALLINT NULL DEFAULT NULL,
  `organisationName` VARCHAR(60) NULL DEFAULT NULL,
  `departmentName` VARCHAR(60) NULL DEFAULT NULL,
  -- `postOfficeBox` VARCHAR(13) NULL DEFAULT NULL,
  `PoBoxNumber` SMALLINT NULL DEFAULT 0,
  -- `streetAddress` VARCHAR(45) NULL DEFAULT NULL, -- ThoroughfareElements (Oakwood Drive)
  `dependentThoroughfare` VARCHAR(80) NULL DEFAULT NULL,
  `thoroughfare` VARCHAR(80) NULL DEFAULT NULL,
  -- `locality` VARCHAR(45) NULL DEFAULT NULL, -- LocalityElements (SOUTHAMPTON)
  `doubleDependentLocality` VARCHAR(35) NULL DEFAULT NULL,
  `dependentLocality` VARCHAR(35) NULL DEFAULT NULL,

  `postTown` VARCHAR(30) NULL DEFAULT NULL, -- UPPERCASE
  -- `region` VARCHAR(30) NULL DEFAULT NULL, -- County

  -- latitude decimal(9,6) NOT NULL -- (50.944221)
  -- longitude decimal(9,6) NOT NULL -- (-1.427960)

  PRIMARY KEY (`countryCode`,`postalCode`,`deliveryPointSuffix`),
  INDEX `fk_address_countryCode` (`countryCode` ASC) VISIBLE,
  INDEX `fk__address_postalCode` (`postalCode` ASC) VISIBLE,
  INDEX `fk__address_deliveryPointSuffix` (`deliveryPointSuffix` ASC) VISIBLE,
  CONSTRAINT `fk_Address_country`
    FOREIGN KEY (`countryCode`)
    REFERENCES `ramp_db`.`Country` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ramp_db`.`GB_Addresses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ramp_db`.`GB_Addresses` ;

CREATE TABLE IF NOT EXISTS `ramp_db`.`GB_Addresses` (
  `UDPRN` VARCHAR(15) NOT NULL, -- (UDPRN:60720866)
  `postalCode` VARCHAR(8) NOT NULL,
  `postTown` VARCHAR(30) NOT NULL,
  `dependentLocality` VARCHAR(35) NULL DEFAULT NULL,
  `doubleDependentLocality` VARCHAR(35) NULL DEFAULT NULL,
  `thoroughfare` VARCHAR(80) NULL DEFAULT NULL,
  `dependentThoroughfare` VARCHAR(80) NULL DEFAULT NULL,
  `buildingNumber` SMALLINT NULL DEFAULT NULL,
  `buildingName` VARCHAR(50) NULL DEFAULT NULL,
  `subBuildingName` VARCHAR(30) NULL DEFAULT NULL,
  `PoBoxNumber` SMALLINT NULL DEFAULT NULL,
  `departmentName` VARCHAR(60) NULL DEFAULT NULL,
  `organisationName` VARCHAR(60) NULL DEFAULT NULL,
  `SUOrgFLAG` TINYINT NOT NULL DEFAULT 0,
  `deliveryPointSuffix` VARCHAR(2) NOT NULL,
  -- addressKey,organisationKey,numberOfHouseholds,localityKey
  -- (page 22) at https://www.poweredbypaf.com/wp-content/uploads/2017/07/Latest-Programmers_guide_Edition-7-Version-6.pdf 
  PRIMARY KEY (`UDPRN`),
  UNIQUE INDEX `UDPRN_UNIQUE` (`UDPRN` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `ramp_db`.`person_address_LOOKUP`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ramp_db`.`LOOKUP_Person_Address` ;

CREATE TABLE IF NOT EXISTS `ramp_db`.`LOOKUP_Person_Address` (
  `FK_Person_uname` VARCHAR(45) NOT NULL,
  `type` VARCHAR(20) NOT NULL, -- (HOME)
  `FK_Address_countryCode` VARCHAR(2) NOT NULL, -- (GB)
  `FK_Address_postalCode` VARCHAR(15) NOT NULL, -- (SO16 8EL)
  `FK_Address_deliveryPointSuffix` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`FK_Person_uname`,`FK_Address_countryCode`,`FK_Address_postalCode`,`FK_Address_deliveryPointSuffix`),
  CONSTRAINT `fk_Address` FOREIGN KEY (`FK_Address_countryCode`,`FK_Address_postalCode`,`FK_Address_deliveryPointSuffix`)
    REFERENCES `ramp_db`.`Address` (`countryCode`,`postalCode`,`deliveryPointSuffix`),
  CONSTRAINT `fk_Person` FOREIGN KEY (`FK_Person_uname`)
    REFERENCES `ramp_db`.`Person` (`uname`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

