-- MySQL Script generated by MySQL Workbench
-- Wed May 27 01:11:13 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema svelte_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `svelte_db` ;

-- -----------------------------------------------------
-- Schema svelte_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `svelte_db` DEFAULT CHARACTER SET utf8 ;
USE `svelte_db` ;

-- -----------------------------------------------------
-- Table `svelte_db`.`AccountType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `svelte_db`.`AccountType` ;

CREATE TABLE IF NOT EXISTS `svelte_db`.`AccountType` (
  `key` INT(11) NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`key`),
  UNIQUE INDEX `key_UNIQUE` (`key` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `svelte_db`.`LoginAccount`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `svelte_db`.`LoginAccount` ;

CREATE TABLE IF NOT EXISTS `svelte_db`.`LoginAccount` (
  `auPK` VARCHAR(45) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `typeID` INT(11) NOT NULL DEFAULT '1',
  `encryptedPassword` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`auPK`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  INDEX `fk_Account_typeID` (`typeID` ASC) VISIBLE,
  UNIQUE INDEX `auPK_UNIQUE` (`auPK` ASC) VISIBLE,
  CONSTRAINT `fk_Account_typeID`
    FOREIGN KEY (`typeID`)
    REFERENCES `svelte_db`.`AccountType` (`key`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `svelte_db`.`CountryList`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `svelte_db`.`CountryList` ;

CREATE TABLE IF NOT EXISTS `svelte_db`.`CountryList` (
  `id` INT(3) NOT NULL,
  `code` VARCHAR(2) NOT NULL,
  `value` VARCHAR(45) NOT NULL,
  `sageCode` VARCHAR(5) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE,
  UNIQUE INDEX `code` (`code` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `svelte_db`.`Person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `svelte_db`.`Person` ;

CREATE TABLE IF NOT EXISTS `svelte_db`.`Person` (
  `uname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `honorificPrefix` VARCHAR(45) NULL DEFAULT NULL,
  `givenName` VARCHAR(45) NULL DEFAULT NULL,
  `additionalNames` VARCHAR(45) NULL DEFAULT NULL,
  `familyName` VARCHAR(45) NULL DEFAULT NULL,
  `postOfficeBox` VARCHAR(45) NULL DEFAULT NULL,
  `streetAddress` VARCHAR(45) NULL DEFAULT NULL,
  `extendedAddress` VARCHAR(45) NULL DEFAULT NULL,
  `locality` VARCHAR(45) NULL DEFAULT NULL,
  `region` VARCHAR(45) NULL DEFAULT NULL,
  `postalCode` VARCHAR(45) NULL DEFAULT NULL,
  `countryListID` INT(11) NULL DEFAULT NULL,
  `telephone` VARCHAR(45) NULL DEFAULT NULL,
  `mobile` VARCHAR(45) NULL DEFAULT NULL,
  `fax` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`uname`),
  INDEX `fk_Person_countryListID` (`countryListID` ASC) VISIBLE,
  UNIQUE INDEX `uname_UNIQUE` (`uname` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  CONSTRAINT `fk_Person_countryListID`
    FOREIGN KEY (`countryListID`)
    REFERENCES `svelte_db`.`CountryList` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
