#!/bin/bash -eu
if [[ "${HOME}" == "/root" ]]; then
  echo "${HOME} IS AN INVALID HOME PATH";
  read -p "Enter (linux) username: " USERNAME;
  HOME="/home/${USERNAME}";
fi

function mkLinkTests {
  cd /usr/share/php/tests
  sudo ln -s ${HOME}/Projects/RAMP/tests/ "ramp"
  cd ${OLDPWD}
}

sudo mkdir -p /usr/share/php/tests
mkdir -p ~/Code/Documentation/coverage ~/Code/Documentation/php ~/Code/packages/deb
sudo chmod 664 /etc/php/*/cli/php.ini
sudo echo "xdebug.mode=develop,debug,coverage" >> /etc/php/*/cli/php.ini
if [ -L /usr/share/php/ramp ]; then
  if [ -L /usr/share/php/tests/ramp ]; then exit 0; fi
  mkLinkTests;
  exit 0;
fi
mkLinkTests
cd /usr/share/php
sudo ln -s ${HOME}/Projects/RAMP/code/ "ramp"
cd ${OLDPWD}
exit 0;
