<?php
/**
 * --------------------------
 * | Do NOT EDIT THIS file. |
 * --------------------------
 * 
 * This file is vital for the correct managangment, ordering, performance delivery and access to the
 * styling (CSS) of your web application / site and it is strongly recommended that you DO NOT edit it.
 * 
 * ----------------------------------------------------------------------------------------------------
 * RAMP - Rapid web application development environment for building flexible, customisable web systems.
 *
 * This program is free software; you can redistribute it and/or modify it under the terms of the
 * GNU General Public License as published by the Free Software Foundation; either version 2 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with this program; if
 * not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301, USA.
 *
 * @author Matt Renyard (renyard.m@gmail.com)
 * @package RAMP
 * @version 0.0.9;
 */
$cssManifest = $_SERVER["DOCUMENT_ROOT"].'/assets/style/import/css.manifest';
if (DEV_MODE && file_exists($cssManifest)) {

  $STYLE_SERVER = '//'.$_SERVER["HTTP_HOST"].'/assets/style';
  $MEDIA_SERVER = '//'.$_SERVER["HTTP_HOST"].'/assets/media';
  $FUNC_SERVER = '//'.$_SERVER["HTTP_HOST"].'/assets/func';

  foreach (file($cssManifest) as $line) {
    $line = trim($line);
    if((strpos($line,';') !== 0) && ( $line !== '')) {

?>    <link rel="stylesheet" href="<?=$STYLE_SERVER; ?>/import/<?=$line; ?>.css">
<?php }} if (isset(\ramp\SETTING::$SCRATCH__CSS)) { foreach (\ramp\SETTING::$SCRATCH__CSS as $cssScratchFile) { ?>
    <link rel="stylesheet" href="<?=$STYLE_SERVER; ?>/scratch/<?=$cssScratchFile; ?>.css">
<?php }} ?>
    <link rel="stylesheet" href="<?=$STYLE_SERVER; ?>/import/icons.css.php">
    <script src="<?=$FUNC_SERVER; ?>/extlibs/modernizr-custom.js"></script>
<?php } else {

  $STYLE_SERVER = '//style.'.$_SERVER["HTTP_HOST"];
  $MEDIA_SERVER = '//media.'.$_SERVER["HTTP_HOST"];
  $FUNC_SERVER = '//func.'.$_SERVER["HTTP_HOST"];
  $mostRecentDate = '2000-01-01'; // date before RAMP
  $dir =  $_SERVER["DOCUMENT_ROOT"].'/assets/style/combined/';
  chdir($dir);
  $matches = glob('*.css');
  if (is_array($matches) && !empty($matches)){
    foreach($matches as $match){
      $date = explode('.', $match)[0];
      $mostRecentDate = ($mostRecentDate < $date) ? $date : $mostRecentDate;
    }
  }
?>    <link rel="stylesheet" href="<?=$STYLE_SERVER; ?>/combined/<?=$mostRecentDate; ?>.css">
    <!-- TODO:mrenyard: Auto add into combined/YYYY-mm-DD.css -->
    <link rel="stylesheet" href="<?=$STYLE_SERVER; ?>/import/icons.css.php">
    <script src="<?=$FUNC_SERVER; ?>/extlibs/modernizr-custom.js"></script>
<?php } ?>
