<?php
/**
 * --------------------------
 * | Do NOT EDIT THIS file. |
 * --------------------------
 * 
 * This file is a vital part of your web application / site accessability features including managing
 * page level tab naviagation and search and it is strongly recommended that you DO NOT edit it.
 * 
 * ----------------------------------------------------------------------------------------------------
 * 
 * RAMP - Rapid web application development environment for building flexible, customisable web systems.
 *
 * This program is free software; you can redistribute it and/or modify it under the terms of the
 * GNU General Public License as published by the Free Software Foundation; either version 2 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with this program; if
 * not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301, USA.
 *
 * @author Matt Renyard (renyard.m@gmail.com)
 * @package RAMP
 * @version 0.0.9;
 * 
 * To give your/our visitors more of a clue to where a link is likely to take them we recommend using some
 * descriptive precursors in the links associated title attribute:
 * 1) 'Jump to ...' - Used with most in-page links to assist in navigating within a page.
 * 2) 'Skip to ...' - Simalar to 'Jump to ...' but with the indication that you are bypassing content ahead. 
 * 3) 'Back to ...' - when returning to content that was previously jumped from.
 * 4) 'Here for ...' - Anchor links that denote the start of a section of content.
 * 5) 'External link to|for ...' - These links will navigate you away from this website to another site.
 * 6) Internal links should/will usually contain the words 'this ...(site|application)' or 'for more on...'
 */
namespace ramp;
?>
      <nav>
        <ul id="quick-links">
          <li><a href="/accessibility#main" title="Interacting with, accessing and getting around this web application">Accessibility</a></li>
          <li><a href="#main" title="Skip to Page Main content: <?=$this->title; ?>">Main Content</a></li>
          <li><a href="#site-nav" title="Jump to Full Site Map (Navigation)">Site Navigation</a></li>
          <li><a href="#contentinfo" title="Jump to Site Information: contact address, legal, copyright and privacy statement etc.">Site Information</a></li>
        </ul>
        <form id="quick-search" method="get" action="/search#results">
          <div class="search input field">
            <label for="query" title="Here to search <?=SETTING::$RAMP_DOMAIN; ?> for the latest content, data and more.">Search</label>
            <input id="query" name="query" type="search" tabindex="0" placeholder="e.g. keyword, contact, organisation.">
            <span class="hint">Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit tempore cum debitis voluptatem alias quos esse nostrum illo repudiandae incidunt. Magnam dolorum iste libero esse odit sit harum corrupti dolore? Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi aliquam, voluptates ad ex ab laborum eveniet quia eos quibusdam deserunt similique ducimus molestias corporis odit ratione laudantium quis nesciunt? Ullam.</span>
          </div>            
          <input type="submit" value="Go">
        </form>
      </nav>
