<?php
/**
 * --------------------------
 * | Do NOT EDIT THIS file. |
 * --------------------------
 * 
 * This file forms the root base for every page on your web application / site and must NOT be edited.
 * The following sub files can be edited by a frount-end developer:
 * 
 * header-logo.php, site-navigation.php, footer.php
 * 
 * -----------------------------------------------------------------------------------------------------
 * RAMP - Rapid web application development environment for building flexible, customisable web systems.
 *
 * This program is free software; you can redistribute it and/or modify it under the terms of the
 * GNU General Public License as published by the Free Software Foundation; either version 2 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with this program; if
 * not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301, USA.
 *
 * @author Matt Renyard (renyard.m@gmail.com)
 * @package RAMP
 * @version 0.0.9;
 */
namespace ramp\view;
$site = WebRoot::getInstance();
?>
<!doctype html>
<html class="no-js" lang="en">
  <head>
    <meta charset="utf-8">
    <title><?=$this->title; ?> - <?=\ramp\SETTING::$RAMP_DOMAIN; ?></title>
    <meta name="description" content="<?=$this->summary; ?>">
    <meta name="viewport" content="width=device-width,initial-scale=1.0,interactive-widget=resizes-content">
<?php include("head.php"); ?>
  </head>
  <body id="<?=str_replace('.', '-', \ramp\SETTING::$RAMP_DOMAIN) ?>" class="<?=$site->pageType; ?>"><!-- $site->pageCategory -->
<?=$site->dialog; ?>
    <header id="top">
<?php include("header-logo.php"); ?>
<?php include("page-navigation.php"); ?>
    </header>
<?=$site->main; ?>
    <nav id="site-nav"><!--a href="#site-nav" title="Here for Full Site Map (Navigation)">#</a-->
<?php include("site-navigation.php"); ?>
    </nav>
    <footer id="contentinfo"><a href="#contentinfo" title="Here for Site Information: contact address, legal, copyright and privacy statement etc.">#</a>
<?php include("footer.php"); ?>
    </footer>
<?=$site->dataLists; ?>
<?php include("scripts.php"); ?>
  </body>
</html>
