<?php
/**
 * --------------------------
 * | Do NOT EDIT THIS file. |
 * --------------------------
 * 
 * This file forms the root base for every page on your web application / site and must NOT be edited.
 * The following sub include files can be edited by a frount-end developer:
 * 
 * /www/header-logo.php, /www/site-navigation.php, /wwww/footer.php
 * 
 * -----------------------------------------------------------------------------------------------------
 * RAMP - Rapid web application development environment for building flexible, customisable web systems.
 *
 * This program is free software; you can redistribute it and/or modify it under the terms of the
 * GNU General Public License as published by the Free Software Foundation; either version 2 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with this program; if
 * not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301, USA.
 *
 * @author Matt Renyard (renyard.m@gmail.com)
 * @package RAMP
 * @version 0.0.9;
 */
namespace ramp;
$site = view\WebRoot::getInstance();
?>
<!doctype html>
<html class="no-js" lang="en">
  <head>
    <meta charset="utf-8">
    <title><?=$this->title; ?> - <?=SETTING::$RAMP_DOMAIN; ?></title>
    <meta name="description" content="<?=$this->summary; ?>">
    <meta name="viewport" content="width=device-width,initial-scale=1.0,interactive-widget=resizes-content">
<?php include("head.php"); ?>
  </head>
  <body id="<?=str_replace('.', '-', SETTING::$RAMP_DOMAIN) ?>" class="<?=$site->pageType; ?>">
<?=$site->dialog; ?>
    <header id="top">
<?php include("page-navigation.php"); ?>
<?php include("header-logo.php"); ?>
    </header>
<?=$site->main; ?>
    <nav id="site-nav" tabindex="-1">
<?php include("site-navigation.php"); ?>
    </nav>
    <footer id="contentinfo">
<?php include("footer.php"); ?>
      <a href="#top" title="Jump back to Top-of-page (in-page Navigation), this is the last link on this page.">top</a>
    </footer>
<?=$site->dataLists; ?>
<?php include("scripts.php"); ?>
  </body>
</html>
