#!/bin/bash -eu

if [[ "$0" != "tools/buildDevEnv" && "$0" != "./tools/buildDevEnv" ]]; then
  echo "Must be run from parent project containing directory NOT $0";
  exit 1;
fi
if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as root" 1>&2;
  exit 1;
fi

if [ $USER == 'root' ]; then USER=$SUDO_USER; HOME="/home/${SUDO_USER}"; fi
while [[ "${HOME}" == "/root" || "${HOME}" == "/home/root" || ! -d "${HOME}" ]]; do
  echo "USER HOME PATH ${HOME} IS INVALID!";
  read -p "Enter username: " USER
  HOME=`echo "/home/${USER}"`;
done
export HOME USER;

LAN=false; LAN_HOSTNAME="${HOSTNAME,,}.lan"; if [[ "${HOSTNAME}" == *.lan ]]; then LAN=true; LAN_HOSTNAME=${HOSTNAME}; fi

trap "closing_message" EXIT
function closing_message {
  if [ $? -ne 0 ]; then
    echo -e "\nBUILD \e[0;31mFAILED WITH ERRORS\e[0m. PLEASE CHECK OUTPUT AND FIX ANY ISSUES BEFORE RE-RUNNING THIS SCRIPT.";
    exit 1;
  fi
  echo -e "\nBUILD COMPLETED \e[0;32mSUCCESSFULLY\e[0m. RAMP DEVELOPMENT ENVIRONMENT IS READY TO USE.";
  echo -e "Documentation for RAMP can be found by navigating to \033[0;47;4;34mhttps://docs.${LAN_HOSTNAME}\033[0m in your web browser,";
  echo -e "and you can access the current example working RAMP application at \033[0;47;4;34mhttp://dev.ramp.${LAN_HOSTNAME}\033[0m";
  exit 0;
}

# RAMP Setup
echo -e "\nSETTING UP RAMP Development Environment...";

echo -e "\nUPDATING APT REPOSITORIES...";
sudo apt update -y;
echo -e "\nUPGRADING EXISTING PACKAGES...";
sudo apt upgrade -y;
echo -e "\nINSTALLing REQUIRED DEPENDENCIES...";
sudo apt install curl -y;

# Apache2 WebShop Configuration (LAMP) Setup
if test -x "$(which webstart)" && curl -sk --head https://misc.${LAN_HOSTNAME}/info.php | head -n 1 | grep "HTTP/1.[01] 200." > /dev/null; then
  echo "Apache2 WebShop Configuration (LAMP) already installed. Skipping...";
else
  echo -e "\nINSTALLing Apache2 WebShop Configuration (LAMP)...";
  sudo apt install openssl postfix apache2 -y;
  sudo ufw allow "Apache Full";
  sudo ufw enable;
  sudo apt install mysql-server -y;
  sudo apt install php php-xdebug libapache2-mod-php php-xml php-mbstring php-gd php-sqlite3 php-mysql -y;
  VERSION=`curl -sk --head https://github.com/mrenyard/Apache2-WebShop-Configuration/releases/latest/ | grep -o "location: https://github.com/mrenyard/Apache2-WebShop-Configuration/releases/tag/v.*" | cut -d"v" -f2- | tr -d "\r"`;
  wget https://github.com/mrenyard/Apache2-WebShop-Configuration/releases/download/v${VERSION}/apache2-webshop-conf_${VERSION}-0_all.deb
  sudo chmod 644 apache2-webshop-conf_${VERSION}-0_all.deb;
  sudo chown ${USER}:${USER} apache2-webshop-conf_${VERSION}-0_all.deb;
  sudo dpkg -i apache2-webshop-conf_${VERSION}-0_all.deb;
  if [ -d /etc/apache2/ssl ]; then sudo rm -rf /etc/apache2/ssl; fi;
  sudo mkdir /etc/apache2/ssl;
  echo "CREATING SELF-SIGNED SSL CERTIFICATE; USE ${LAN_HOSTNAME} as FDQN";
  sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/apache2/ssl/apache.key -out /etc/apache2/ssl/apache.crt;
  sudo chown root:ssl-cert /etc/apache2/ssl/*;
  sudo chmod 710 /etc/apache2/ssl/*;
  sudo webstart;
  sudo rm apache2-webshop-conf_${VERSION}-0_all.deb;
  echo "  Apache2 WebShop Configuration (LAMP) INSTALLED...";
fi

# Web Project Management Tools Setup
if test -x "$(which webproject)" && test -x "$(which virtualhost)"; then
  echo "Web Project Management Tools already installed. Skipping...";
else
  echo -e "\nINSTALLing Web Project Management Tools for WebShop...";
  sudo apt install httrack mmv -y;
  VERSION=`curl -sk --head https://github.com/mrenyard/Web-Project-Managment-Tools/releases/latest/ | grep -o "location: https://github.com/mrenyard/Web-Project-Managment-Tools/releases/tag/v.*" | cut -d"v" -f2- | tr -d "\r"`;
  wget https://github.com/mrenyard/Web-Project-Managment-Tools/releases/download/v${VERSION}/webproject-tools_${VERSION}-0_all.deb;
  sudo chmod 644 webproject-tools_${VERSION}-0_all.deb;
  sudo chown ${USER}:${USER} webproject-tools_${VERSION}-0_all.deb;
  sudo dpkg -i webproject-tools_${VERSION}-0_all.deb;
  sudo rm webproject-tools_${VERSION}-0_all.deb;
  echo "  Web Project Management Tools for WebShop INSTALLED...";
fi

# link assets (FUNC.js, STyLE & MEDIA)
cd ${HOME}/Projects/;
if [ ! -L ${HOME}/Projects/RAMP/www/assets/func ]; then
  if [ ! -d ${HOME}/Projects/FUNC.js ]; then
    echo -e "\nCLONING FUNC.js REPOSITORY...";
    git clone https://github.com/mrenyard/FUNC.js.git ${HOME}/Projects/FUNC.js;
    sudo chown -R ${USER}:${USER} ${HOME}/Projects/FUNC.js;
  fi
  echo -e "\nLINKING RAMP FUNC.js ASSET...";
  ln -s ${HOME}/Projects/FUNC.js/ ${HOME}/Projects/RAMP/www/assets/func
fi
if [ ! -L ${HOME}/Projects/RAMP/www/assets/media ]; then
  if [ ! -d ${HOME}/Projects/MEDIA ]; then
    echo -e "\nCLONING MEDIA REPOSITORY...";
    git clone https://github.com/mrenyard/MEDIA.git ${HOME}/Projects/MEDIA;
    sudo chown -R ${USER}:${USER} ${HOME}/Projects/MEDIA;
  fi
  echo -e "\nLINKING RAMP MEDIA ASSET...";
  sudo ln -s ${HOME}/Projects/MEDIA/ ${HOME}/Projects/RAMP/www/assets/media
fi
if [ ! -L ${HOME}/Projects/RAMP/www/assets/style ]; then
  if [ ! -d ${HOME}/Projects/STyLE ]; then
    echo -e "\nCLONING STyLE REPOSITORY...";
    git clone https://github.com/mrenyard/STyLE.git ${HOME}/Projects/STyLE;
    sudo chown -R ${USER}:${USER} ${HOME}/Projects/STyLE;
  fi
  echo -e "\nLINKING RAMP STyLE ASSET...";
  sudo ln -s ${HOME}/Projects/STyLE/ ${HOME}/Projects/RAMP/www/assets/style
fi
if ( ! curl -sk --head https://ramp.${LAN_HOSTNAME}/index.html | head -n 1 | grep "HTTP/1.[01] 200." > /dev/null;); then
  sudo virtualhost "RAMP" add ramp;
  sudo webstart;
fi

echo -e "\nCREATING development database (ramp_db) with dummy data...";
sudo mysql -e "DROP USER IF EXISTS 'RAMP'@'localhost';"
cd ${HOME}/Projects/RAMP/03-D.A.T.A.design && sudo mysql < ramp_db.sql && sudo mysql < dummy_data.sql && cd $OLDPWD
read -p "Please provide password for RAMP user: " PASSWORD
sudo mysql -e "CREATE USER 'RAMP'@'localhost' IDENTIFIED BY '${PASSWORD}'; GRANT ALL PRIVILEGES ON ramp_db.* TO 'RAMP'@'localhost'; FLUSH PRIVILEGES;"
echo "  Development database (ramp_db) CREATED...";

if [ ! -f ${HOME}/Projects/RAMP/ramp.ini ]; then
  echo -e "\nCreating RAMP configuration file...";
  sudo cp ${HOME}/Projects/RAMP/ramp.ini.example ${HOME}/Projects/RAMP/ramp.ini;
  sudo sed -i -e "s/;domain =/domain = \"ramp.${LAN_HOSTNAME}\"/g" ${HOME}/Projects/RAMP/ramp.ini
  sudo sed -i -e "s/;local_dir =/local_dir = ${HOME//\//\\\/}\/Projects\/RAMP\/local/g" ${HOME}/Projects/RAMP/ramp.ini
  sudo sed -i -e 's/;business_model_manager =/business_model_manager = ramp\\model\\business\\SQLBusinessModelManager/g' ${HOME}/Projects/RAMP/ramp.ini
  sudo sed -i -e 's/;business_model_namespace =/business_model_namespace = ramp\\model\\business/g' ${HOME}/Projects/RAMP/ramp.ini
  sudo sed -i -e 's/;authenticatable_unit =/authenticatable_unit = Person/g' ${HOME}/Projects/RAMP/ramp.ini
  sudo sed -i -e 's/;connection =/connection = "mysql:host=localhost;dbname=ramp_db"/g' ${HOME}/Projects/RAMP/ramp.ini
  sudo sed -i -e 's/;user =/user = RAMP/g' ${HOME}/Projects/RAMP/ramp.ini
  sudo sed -i -e "s/;password =/password = ${PASSWORD}/g" ${HOME}/Projects/RAMP/ramp.ini
  read -p "Please provide SALT value used for password encryption: " SALT
  sudo sed -i -e "s/;password_salt =/password_salt = \"${SALT}\"/g" ${HOME}/Projects/RAMP/ramp.ini
  sudo sed -i -e 's/;from_name =/from_name = "RAMP Administration Team"/g' ${HOME}/Projects/RAMP/ramp.ini
  sudo sed -i -e "s/;from_address =/from_address = no-reply@${LAN_HOSTNAME}/g" ${HOME}/Projects/RAMP/ramp.ini
  sudo sed -i -e "s/;reply_address =/reply_address = support@${LAN_HOSTNAME}/g" ${HOME}/Projects/RAMP/ramp.ini
  sudo sed -i -e 's/;welcome_template =/welcome_template = welcome-email/g' ${HOME}/Projects/RAMP/ramp.ini
  sudo sed -i -e 's/;welcome_template_type =/welcome_template_type = text/g' ${HOME}/Projects/RAMP/ramp.ini
  sudo sed -i -e 's/;welcome_subject_line =/welcome_subject_line = "Welcome to RAMP - All you need, login and more..."/g' ${HOME}/Projects/RAMP/ramp.ini
  sudo chown ${USER}:${USER} ${HOME}/Projects/RAMP/ramp.ini;
  echo "   RAMP configuration file CREATED...";
fi

echo -e "\nPreparing RAMP tests, code coverage and documentation...";
cd ${HOME}/Projects/RAMP;
#sudo tools/test;
sudo tools/document;
cd ${OLDPWD};

function mkLinkTests {
  cd /usr/share/php/tests
  sudo ln -s ${HOME}/Projects/RAMP/tests/ "ramp"
  cd ${OLDPWD}
}
sudo mkdir -p /usr/share/php/tests
chmod 664 /etc/php/*/cli/php.ini
sudo echo "xdebug.mode=develop,debug,coverage" >> /etc/php/*/cli/php.ini
if [ -L /usr/share/php/ramp ]; then
  if [ -L /usr/share/php/tests/ramp ]; then exit 0; fi
  mkLinkTests;
  exit 0;
fi
mkLinkTests
cd /usr/share/php
sudo ln -s ${HOME}/Projects/RAMP/code/ "ramp"
cd ${OLDPWD}
exit 0;
