#!/bin/bash -eu

if [[ "$0" != "tools/buildDevEnv" && "$0" != "./tools/buildDevEnv" ]]; then
  echo "Must be run from parent project containing directory NOT $0";
  exit 1;
fi
if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as root" 1>&2;
  exit 1;
fi

if [ $USER == 'root' ]; then USER=$SUDO_USER; HOME="/home/${SUDO_USER}"; fi
while [[ "${HOME}" == "/root" || ! -d "${HOME}" ]]; do
  echo "USER HOME PATH ${HOME} IS INVALID!";
  read -p "Enter username: " USER
  HOME=`echo "/home/${USER}"`;
done
export HOME USER;

LAN=false; LAN_HOSTNAME="${HOSTNAME,,}.lan"; if [[ "${HOSTNAME}" == *.lan ]]; then LAN=true; LAN_HOSTNAME=${HOSTNAME}; fi

# RAMP Setup
echo -e "\nSETTING UP RAMP Development Environment...";

echo -e "\nUPDATING APT REPOSITORIES...";
sudo apt update -y;
echo -e "\nUPGRADING EXISTING PACKAGES...";
sudo apt upgrade -y;
echo -e "\nINSTALLing REQUIRED DEPENDENCIES...";
sudo apt install curl -y;

# Apache2 WebShop Configuration (LAMP) Setup
if test -x "$(which webstart)" && curl -sk --head https://misc.${LAN_HOSTNAME}/info.php | head -n 1 | grep "HTTP/1.[01] 200." > /dev/null; then
  echo "Apache2 WebShop Configuration (LAMP) already installed. Skipping...";
else
  echo -e "\nINSTALLing Apache2 WebShop Configuration (LAMP)...";
  sudo apt install openssl postfix apache2 -y;
  sudo ufw allow "Apache Full";
  sudo ufw enable;
  sudo apt install mysql-server -y;
  sudo apt install php php-xdebug libapache2-mod-php php-xml php-mbstring php-gd php-sqlite3 php-mysql -y;
  VERSION=`curl -sk --head https://github.com/mrenyard/Apache2-WebShop-Configuration/releases/latest/ | grep -o "location: https://github.com/mrenyard/Apache2-WebShop-Configuration/releases/tag/v.*" | cut -d"v" -f2- | tr -d "\r"`;
  wget https://github.com/mrenyard/Apache2-WebShop-Configuration/releases/download/v${VERSION}/apache2-webshop-conf_${VERSION}-0_all.deb
  sudo chmod 644 apache2-webshop-conf_${VERSION}-0_all.deb;
  sudo chown ${USER}:${USER} apache2-webshop-conf_${VERSION}-0_all.deb;
  sudo dpkg -i apache2-webshop-conf_${VERSION}-0_all.deb;
  if [ -d /etc/apache2/ssl ]; then sudo rm -rf /etc/apache2/ssl; fi;
  sudo mkdir /etc/apache2/ssl;
  echo "CREATING SELF-SIGNED SSL CERTIFICATE; USE ${LAN_HOSTNAME} as FDQN";
  sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/apache2/ssl/apache.key -out /etc/apache2/ssl/apache.crt;
  sudo chown root:ssl-cert /etc/apache2/ssl/*;
  sudo chmod 710 /etc/apache2/ssl/*;
  sudo webstart;
  sudo rm apache2-webshop-conf_${VERSION}-0_all.deb;
  echo "  Apache2 WebShop Configuration (LAMP) INSTALLED...";
fi

# Web Project Management Tools Setup
if test -x "$(which webproject)" && test -x "$(which virtualhost)"; then
  echo "Web Project Management Tools already installed. Skipping...";
else
  echo "INSTALLing Web Project Management Tools for WebShop...";
  sudo apt install httrack mmv -y;
  VERSION=`curl -sk --head https://github.com/mrenyard/Web-Project-Managment-Tools/releases/latest/ | grep -o "location: https://github.com/mrenyard/Web-Project-Managment-Tools/releases/tag/v.*" | cut -d"v" -f2- | tr -d "\r"`;
  wget https://github.com/mrenyard/Web-Project-Managment-Tools/releases/download/v${VERSION}/webproject-tools_${VERSION}-0_all.deb;
  sudo chmod 644 webproject-tools_${VERSION}-0_all.deb;
  sudo chown ${USER}:${USER} webproject-tools_${VERSION}-0_all.deb;
  sudo dpkg -i webproject-tools_${VERSION}-0_all.deb;
  sudo rm webproject-tools_${VERSION}-0_all.deb;
  echo "  Web Project Management Tools for WebShop INSTALLED...";
fi

# link assets (FUNC.js, STyLE & MEDIA)
cd ${HOME}/Projects/;
if [ ! -L ${HOME}/Projects/RAMP/assets/func ]; then
  if [ ! -d ${HOME}/Projects/FUNC.js ]; then
    echo -e "\nCLONING FUNC.js REPOSITORY...";
    git clone https://github.com/mrenyard/FUNC.js.git
    sudo chown -R ${USER}:${USER} ${HOME}/Projects/FUNC.js;
  fi
  echo -e "\nLINKING RAMP FUNC.js ASSET...";
  sudo ln -s ${HOME}/Projects/RAMP/assets/func ${HOME}/Projects/FUNC.js/
fi
if [ ! -L ${HOME}/Projects/RAMP/assets/media ]; then
  if [ ! -d ${HOME}/Projects/MEDIA ]; then
    echo -e "\nCLONING MEDIA REPOSITORY...";
    git clone https://github.com/mrenyard/MEDIA.git
    sudo chown -R ${USER}:${USER} ${HOME}/Projects/MEDIA;
  fi
  echo -e "\nLINKING RAMP MEDIA ASSET...";
  sudo ln -s ${HOME}/Projects/RAMP/assets/media ${HOME}/Projects/MEDIA/
fi
if [ ! -L ${HOME}/Projects/RAMP/assets/style ]; then
  if [ ! -d ${HOME}/Projects/STyLE ]; then
    echo -e "\nCLONING STyLE REPOSITORY...";
    git clone https://github.com/mrenyard/STyLE.git
    sudo chown -R ${USER}:${USER} ${HOME}/Projects/STyLE;
  fi
  echo -e "\nLINKING RAMP STyLE ASSET...";
  sudo ln -s ${HOME}/Projects/RAMP/assets/style ${HOME}/Projects/STyLE/
fi
if ( ! curl -sk --head https://ramp.${LAN_HOSTNAME}/index.html | head -n 1 | grep "HTTP/1.[01] 200." > /dev/null;); then
  echo -e "\nAdd webproject \"RAMP\" new...";
  sudo webproject "RAMP" new;
  sudo webstart;
fi

function mkLinkTests {
  cd /usr/share/php/tests
  sudo ln -s ${HOME}/Projects/RAMP/tests/ "ramp"
  cd ${OLDPWD}
}
sudo mkdir -p /usr/share/php/tests
chmod 664 /etc/php/*/cli/php.ini
sudo echo "xdebug.mode=develop,debug,coverage" >> /etc/php/*/cli/php.ini
if [ -L /usr/share/php/ramp ]; then
  if [ -L /usr/share/php/tests/ramp ]; then exit 0; fi
  mkLinkTests;
  exit 0;
fi
mkLinkTests
cd /usr/share/php
sudo ln -s ${HOME}/Projects/RAMP/code/ "ramp"
cd ${OLDPWD}
exit 0;
